spring.application.name=backend-api

# --- CONFIGURACIÓN DE LA CONEXIÓN A ORACLE (CORREGIDA) ---
# Usamos XEPDB1 y el usuario que creamos en el script
spring.datasource.url=jdbc:oracle:thin:@oracle_esiligue:1521/XEPDB1
spring.datasource.username=esiligue_admin
spring.datasource.password=uca_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- CONFIGURACIÓN DE JPA / HIBERNATE ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true